name: hikees
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+8

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  json_annotation: ^4.4.0
  shared_preferences: ^2.0.6
  cupertino_icons: ^1.0.2
  line_awesome_flutter: ^1.1.0-nullsafety
  google_fonts: ^2.3.1
  carousel_slider: ^4.0.0
  flutter_rating_bar: ^4.0.0
  google_polyline_algorithm: ^3.1.0
  fl_chart: ^0.46.0
  csv: ^5.0.0
  url_launcher: ^6.0.9
  get_it: ^7.2.0
  cached_network_image: ^3.1.0
  shimmer: ^2.0.0
  flutter_slidable: ^1.2.0
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^5.0.2
  image_picker: ^0.8.4+4
  tuple: ^2.0.0
  intl: ^0.17.0
  get: ^4.6.1
  add_2_calendar: ^2.1.1
  flutter_flavor: ^3.0.3
  background_locator: 1.6.6
  permission_handler: ^8.2.5
  readmore: ^2.1.0
  marquee: ^2.2.0
  auto_size_text: ^3.0.0-nullsafety.0
  photo_view: ^0.13.0
  flutter_svg: ^0.23.0+1
  syncfusion_flutter_sliders: ^19.3.54
  flutter_map: ^0.14.0
  flutter_map_location_marker: ^3.0.2
  proj4dart: ^2.0.0
  uni_links: ^0.5.1
  flutter_launcher_icons: ^0.9.2
  share_plus: ^3.1.0
  geoimage: ^0.2.0
  path_provider: ^2.0.9
  dio: ^4.0.4
  sqflite: ^2.0.2
  geolocator: ^8.2.0
  flutter_compass: ^0.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  json_serializable: ^6.1.6
  analyzer: ^4.0.0
dependency_overrides:
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: master
  flutter_compass:
    git:
      url: https://github.com/hemanthrajv/flutter_compass
      ref: master
flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/icon/ios_icon.png"
  image_path_android: "assets/icon/android_icon.png"
  adaptive_icon_foreground: "assets/icon/icon.png"
  adaptive_icon_background: "#1ec28c"
  remove_alpha_ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/not_available.jpg
    - assets/images/lands_department.png
    - assets/data/
  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Regular.otf
        - asset: fonts/Gilroy-Medium.otf
          weight: 500
        - asset: fonts/Gilroy-Bold.otf
          weight: 700
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
